#!/usr/bin/expect

set timeout 6
set user [lindex $argv 0]
set ip [lindex $argv 1]
set password [lindex $argv 2]

spawn ssh-copy-id -i ~/.ssh/id_rsa.pub $user@$ip
expect {
    # first connection, no public key in ~/.ssh/known_hosts
    "yes/no" {
    send "yes\r"
    expect "password:"
        send "$password\r"：
    
    }
    # already has public key in ~/.ssh/known_hosts
    "password:" {
        send "$password\r"
    
    }
}
expect eof

